#!/bin/bash
# Example usage scripts for syngen

echo "Example 1: Generate 10 rows of customer data as CSV"
echo "Command: python3 syngen.py --rows 10 --output examples/customers.csv --format csv"
echo ""
echo "When prompted, you could enter:"
echo "  3 fields"
echo "  Field 1: customer_id (integer, min: 1, max: 10000)"
echo "  Field 2: email (email)"
echo "  Field 3: signup_date (date, 2024-01-01 to 2024-12-31)"
echo ""
echo "---"
echo ""
echo "Example 2: Generate 50 users as JSON"
echo "Command: python3 syngen.py --rows 50 --output examples/users.json --format json"
echo ""
echo "---"
echo ""
echo "Example 3: Generate SQL inserts for a products table"
echo "Command: python3 syngen.py --rows 100 --output examples/products.sql --format sql --table products"
echo ""
echo "When prompted, you could enter:"
echo "  5 fields"
echo "  Field 1: product_id (integer, min: 1, max: 10000)"
echo "  Field 2: product_name (string, length: 20)"
echo "  Field 3: price (float, min: 9.99, max: 999.99, precision: 2)"
echo "  Field 4: in_stock (boolean, probability: 0.8)"
echo "  Field 5: created_at (datetime)"
echo ""
